# Generated by Django 3.2 on 2021-05-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_name', models.CharField(max_length=100)),
                ('pass_mobile', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('pass_address', models.TextField(null=True)),
                ('aadhar', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(max_length=20)),
                ('foodreqd', models.BooleanField(default=False, verbose_name='Food required')),
                ('railwaypasscon', models.BooleanField(default=False, verbose_name='Railway Pass Concession')),
                ('carr', models.CharField(choices=[('ec', 'Exec. Chair Car'), ('2a', 'AC 2 Tier'), ('fc', 'First Class'), ('3a', 'AC 3 Tier'), ('3e', 'AC 3 Economy'), ('cc', 'Chair Car'), ('sl', 'Sleeper'), ('2s', 'Second Sitting')], default='All Classes', max_length=20)),
                ('bag_weight', models.FloatField()),
                ('dateofdeparture', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
