# Generated by Django 3.2 on 2021-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railwaybooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketinfo',
            options={'ordering': ['-dor']},
        ),
        migrations.RemoveField(
            model_name='ticketinfo',
            name='pass_mobile',
        ),
        migrations.AddField(
            model_name='ticketinfo',
            name='dor',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketinfo',
            name='weight',
            field=models.FloatField(default=12.3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketinfo',
            name='aadhar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='ticketinfo',
            table='Bookings',
        ),
    ]
