# Generated by Django 3.2 on 2021-05-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railwaybooking', '0002_auto_20210503_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketinfo',
            name='weight',
        ),
        migrations.AlterField(
            model_name='ticketinfo',
            name='dateofdeparture',
            field=models.DateField(),
        ),
    ]
